import type { GuideCopy } from "./types";
import { officialLinks } from "./shared";

export const be = {
  locale: "be",
  htmlLang: "be",
  languageName: "Беларуская",
  shortLanguageName: "BE",
  meta: {
    title: "EDD для WordPress-тэм з дапамогай ШІ",
    description:
      "Практычны дапаможнік па Eval-Driven Development для распрацоўкі ўласных WordPress-тэм з дапамогай ШІ.",
  },
  skipLink: "Прапусціць навігацыю",
  brand: {
    name: "EDD для WordPress",
    subtitle: "Практычны дапаможнік",
    homeLabel: "EDD для WordPress — пачатак",
  },
  nav: {
    label: "Асноўная навігацыя",
    basics: "Асновы",
    tools: "Інструменты",
    architecture: "Архітэктура",
    start: "Старт",
    checklist: "Кантрольны спіс",
  },
  languageMenu: { label: "Выбраць мову", current: "Беларуская" },
  hero: {
    eyebrow: "Дапаможнік для пачаткоўцаў · 2026",
    titleLine1: "ШІ піша код.",
    titleLine2: "Эвалы даказваюць, што ён працуе.",
    lede:
      "Як укараніць Eval-Driven Development у распрацоўку ўласнай тэмы WordPress — без стварэння новага фрэймворку, без MCP там, дзе ён не патрэбны, і без спадзявання на «выглядае нармальна».",
    primaryCta: "Паглядзець рэкамендаваную архітэктуру",
    secondaryCta: "Адкрыць прыклады",
    notePrefix: "Рэкамендацыя адным сказам:",
    noteStrong: "тэсты разам з праектам",
    noteSuffix:
      ", адна лакальная каманда eval і дадатковы Promptfoo толькі для параўнання агентаў.",
    visualLabel: "Працэс Eval-Driven Development",
    flowCards: [
      { number: "01", title: "Задача", text: "ясны намер" },
      { number: "02", title: "ШІ-агент", text: "змяняе тэму" },
      { number: "03", title: "Eval harness", text: "запускае грэйдары" },
      { number: "04", title: "Доказ", text: "pass / fail + артэфакты" },
    ],
    core: "EDD",
    coreText: "вымернае\n«гатова»",
    caption: "Рэалізуй → правер → выпраў → паўтары",
  },
  signals: {
    label: "Ключавыя прынцыпы",
    items: [
      { title: "Спачатку дэтэрміністычнае", text: "найбольш стабільны сігнал" },
      { title: "Доказ для кожнага fail", text: "trace, лог або скрыншот" },
      { title: "Агент не змяняе крытэрый", text: "эваль застаецца незалежным" },
    ],
  },
  basics: {
    kicker: "01 · Асновы",
    title: "Што такое эваль — без магіі?",
    intro:
      "Эваль — гэта паўтаральная праверка, якая пры вядомым уводзе вымярае, ці дасягнула сістэма загадзя вызначанага выніку. У распрацоўцы з дапамогай ШІ вымяраецца вынік агента, а не тое, наколькі пераканаўча гучыць яго адказ.",
    cards: [
      { letter: "A", title: "Увод", text: "Задача, зыходны рэпазіторый, fixture-даныя, viewport і ўсе дазволеныя інструменты." },
      { letter: "B", title: "Чаканы вынік", text: "Канкрэтны крытэрый: меню закрываецца клавішай Escape, няма памылкі PHP, няма overflow." },
      { letter: "C", title: "Грэйдар", text: "Найпрасцейшы надзейны спосаб вымярэння: assertion, лінтар, browser-тэст або вузкая рубрыка." },
      { letter: "D", title: "Доказ", text: "Pass/fail, фактычнае значэнне, лог, trace, скрыншот і версіі асяроддзя." },
    ],
    loopLabel: "Цыкл EDD ад крытэрыю да выпраўлення",
    loop: [
      { number: "1", text: "Вызнач «гатова»" },
      { number: "2", text: "Запусці baseline" },
      { number: "3", text: "ШІ рэалізуе" },
      { number: "4", text: "Эваль вымярае" },
      { number: "5", text: "Выпраў прычыну" },
    ],
  },
  graders: {
    kicker: "Правіла выбару",
    title: "Найтаннейшы грэйдар, які надзейна бачыць памылку",
    intro:
      "LLM-as-a-judge карысны, але не павінен вырашаць задачу, якую DOM, парсер, exit code або browser assertion вырашае дакладней.",
    deterministic: {
      overline: "Першы выбар",
      title: "Дэтэрміністычны грэйдар",
      text: "Адзін і той самы стан дае аднолькавы, вытлумачальны вынік. Ён хуткі, танны і ідэальны як вароты CI.",
      tagsLabel: "Прыклады дэтэрміністычных праверак",
      tags: ["HTTP 200", "роўна адзін H1", "няма overflow", "PHPCS exit 0", "Escape закрывае меню", "парог pixel diff"],
      exampleLabel: "Прыклад",
      example: "scrollWidth > clientWidth → FAIL",
    },
    model: {
      overline: "Толькі калі трэба",
      title: "Мадэльны грэйдар",
      text: "Для нюансаў, якія немэтазгодна зводзіць да правіла. Рубрыка мусіць быць вузкай, прывязанай да эталона і загадзя адкалібраванай.",
      tagsLabel: "Прыклады мадэльных ацэнак",
      tags: ["адпаведнасць Figma", "візуальная іерархія", "зразумеласць UX рэдактара", "архітэктурная ацэнка"],
      exampleLabel: "Добрая рубрыка",
      example: "Ацані толькі spacing і alignment ад 0 да 5.",
    },
    ladderLabel: "Парадак выбару грэйдара",
    ladder: ["assertion", "наяўны інструмент", "ўласны скрыпт", "мадэльная рубрыка"],
  },
  tools: {
    kicker: "02 · Інструменты",
    title: "Які інструмент бачыць які тып памылкі?",
    intro:
      "Вам не патрэбны адзін «супер-ацэншчык». Складзіце невялікія спецыялізаваныя грэйдары і выкарыстоўвайце кожны толькі там, дзе яго сігнал надзейны.",
    boundaryLabel: "Мяжа",
    items: [
      { mark: "PW", name: "Playwright", tone: "mint", use: "Крытычныя карыстальніцкія сцэнары, адаптыўныя паводзіны, мабільнае меню, формы, памылкі кансолі і гарызантальны overflow.", notFor: "Гэта не замена unit-тэстам; не варта тэставаць ім кожную дробязь.", link: officialLinks.playwright, linkLabel: "Дакументацыя Playwright" },
      { mark: "AX", name: "axe-core", tone: "violet", use: "Праблемы даступнасці, якія аўтаматычна выяўляюцца: назвы элементаў кіравання, кантраст, ARIA і частка правілаў WCAG.", notFor: "Аўтаматыка не даказвае, што ўвесь сайт даступны; клавіятура і screen reader таксама патрабуюць ручной праверкі.", link: officialLinks.axe, linkLabel: "Дакументацыя axe-core" },
      { mark: "CS", name: "PHPCS + WPCS", tone: "amber", use: "Канвенцыі WordPress coding, папярэджанні пра escaping, інтэрнацыяналізацыя і паўтаральныя праверкі PHP-кода.", notFor: "Праходжанне стандартаў не азначае, што бізнес-логіка правільная.", link: officialLinks.wpcs, linkLabel: "Стандарты WordPress PHP" },
      { mark: "PS", name: "PHPStan", tone: "blue", use: "Статычны аналіз: невядомыя класы і метады, няправільныя тыпы, мёртвыя галіны і падазроныя выклікі да runtime.", notFor: "Для дынамічнага кода WordPress патрэбныя паступовая наладка і адпаведныя stubs або пашырэнні.", link: officialLinks.phpstan, linkLabel: "Пачатковы дапаможнік PHPStan" },
      { mark: "LH", name: "Lighthouse CI", tone: "coral", use: "Бюджэты для прадукцыйнасці, памеру рэсурсаў і выбраных вынікаў аудыту Lighthouse у кантраляваным асяроддзі.", notFor: "Адзін лабараторны вынік — не тое самае, што рэальныя даныя Core Web Vitals карыстальнікаў.", link: officialLinks.lighthouse, linkLabel: "Lighthouse CI" },
      { mark: "VR", name: "Visual regression", tone: "pink", use: "Параўнанне скрыншотаў ключавых шаблонаў і кампанентаў для выяўлення нечаканых візуальных змен.", notFor: "Baseline не абнаўляецца толькі дзеля таго, каб тэст стаў зялёным; розніцу спачатку павінен прагледзець чалавек.", link: officialLinks.visual, linkLabel: "Візуальныя параўнанні Playwright" },
      { mark: "WP", name: "WP-CLI fixtures", tone: "green", use: "Паўтаральнае стварэнне допісаў, меню, карыстальнікаў, опцый і кантэнтных edge case-аў перад browser-тэстам.", notFor: "Fixture-даныя не з’яўляюцца вытворчым кантэнтам і не павінны трапіць у production-пакет тэмы.", link: officialLinks.wpcli, linkLabel: "Каманды WP-CLI" },
      { mark: "PU", name: "PHPUnit / WP test suite", tone: "slate", use: "Дэтэрміністычная PHP-логіка, фільтры, helpers і інтэграцыі, якія хутчэй праверыць без browser.", notFor: "Не можа пацвердзіць рэальны layout, фокус або ўзаемадзеянне ў browser.", link: officialLinks.phpunit, linkLabel: "Шаблон тэстаў тэмы WordPress" },
    ],
  },
  architecture: {
    kicker: "03 · Архітэктура",
    title: "Пачынайце лакальна. Цэнтралізуйце толькі тое, што паўтараецца.",
    intro: "Для першага праекта дастаткова repo-local harness. Цэнтральны registry, Promptfoo і MCP — дадатковыя слаі, а не ўмова працы эвалоў.",
    local: {
      badge: "Абавязкова",
      title: "Лакальны execution plane",
      intro: "Тут знаходзяцца код, WordPress, browser і фактычны runtime-доказ.",
      items: [
        { number: "01", title: "Зыходны код тэмы", text: "ШІ змяняе рэалізацыю" },
        { number: "02", title: "Наладка fixture", text: "WP-CLI або невялікі dev-only убудова" },
        { number: "03", title: "Каманды eval", text: "PHPCS · PHPStan · Playwright · axe" },
        { number: "04", title: "Доказ", text: "JSON · лог · trace · скрыншот" },
      ],
    },
    bridge: ["версійны bundle", "структураваныя вынікі"],
    central: {
      badge: "Пазней, пры неабходнасці",
      title: "Цэнтральны control plane",
      intro: "Тут знаходзяцца агульныя правілы, гісторыя і абароненыя gate-ы.",
      items: [
        { number: "A", title: "Агульныя стандарты", text: "карпаратыўныя WPCS · a11y · прадукцыйнасць" },
        { number: "B", title: "Bundle праекта", text: "дакладная, зафіксаваная версія эвалоў" },
        { number: "C", title: "Схаваныя / release-эвалы", text: "праверкі edge case і policy" },
        { number: "D", title: "Гісторыя запускаў", text: "трэнды · параўнанні · рашэнні" },
      ],
    },
    ruleLabel: "Узнаўляльнасць:",
    rule: "source commit + версія eval bundle + версія fixture + версія runtime = паўтаральны запуск eval.",
  },
  promptfoo: {
    kicker: "04 · Promptfoo",
    title: "Эксперыментальны слой, а не грэйдар WordPress",
    intro: "Promptfoo запускае матрыцу prompt-аў, provider-аў і тэставых выпадкаў, прымяняе assertions і параўноўвае вынікі. Вашы інструменты WordPress па-ранейшаму даказваюць, што тэма працуе.",
    flowLabel: "Роля Promptfoo ў сістэме eval",
    inputs: ["prompt A", "prompt B", "мадэль / агент"],
    coreOverline: "experiment runner",
    coreText: "аднолькавыя задачы · кантраляваная змена",
    graders: ["Playwright", "PHPCS", "axe", "custom assertion"],
    resultOverline: "рашэнне",
    resultTitle: "baseline vs candidate",
    resultText: "якасць · кошт · працягласць",
    yesLabel: "ТАК, калі…",
    yes: ["параўноўваеце два prompt-ы на адных і тых жа задачах;", "вымяраеце некалькі мадэляў або канфігурацый reasoning;", "маеце больш за 20 паўтаральных задач для coding-agent;", "хочаце гісторыю і матрыцу вынікаў без уласнага UI."],
    noLabel: "ЯШЧЭ НЕ, калі…",
    no: ["толькі ўводзіце першы тэст Playwright;", "не параўноўваеце агентаў або prompt-ы;", "вам патрэбна толькі адна надзейная лакальная каманда;", "асяроддзе WordPress fixture яшчэ не стабільнае."],
    cautionLabel: "Пясочніца",
    cautionBefore: "Запускайце coding-agent eval у",
    cautionStrong: "disposable workspace",
    cautionAfter: ", без вытворчых уліковых даных і рэальных даных кліента. Дакументацыя Promptfoo прама папярэджвае, што coding agents выконваюць адвольны код.",
    cautionLink: "Афіцыйны дапаможнік па coding-agent eval",
  },
  mcp: {
    kicker: "05 · MCP",
    title: "MCP — гэта слой доступу, а не test runner",
    intro: "MCP стандартызуе тое, як ШІ-праграма выяўляе і выклікае tools, чытае resources і выкарыстоўвае prompts. Ён не вызначае, як павінны быць рэалізаваныя вашы Playwright, WordPress або CI.",
    yesTitle: "MCP мае сэнс для",
    yes: ["атрымання eval bundle праекта;", "чытання цэнтральных стандартаў і вядомых рэгрэсій;", "адпраўкі структураваных вынікаў і метаданых артэфактаў;", "параўнання папярэдніх запускаў з некалькіх праектаў;", "аўтарызаванага доступу да цэнтральнага мадэльнага грэйдара."],
    noTitle: "MCP не патрэбны для",
    no: ["лакальнага запуску npx playwright test;", "PHPCS, PHPStan і build-каманд, якія агент ужо можа выклікаць;", "захоўвання project-specific тэстаў разам з кодам;", "WP-CLI seed і reset у лакальным інстансе;", "першай версіі eval harness."],
    sourcePrefix: "Прачытайце:",
    sourceLink: "афіцыйны агляд архітэктуры MCP",
  },
  setup: {
    kicker: "06 · Мінімальная наладка",
    title: "Разам з зыходным кодам тэмы — але не ў production ZIP",
    intro: "Рэпазіторый — сапраўдная мяжа. Тэсты застаюцца прывязанымі да commit тэмы, а ZIP для пастаўкі змяшчае толькі runtime-файлы.",
    repoPanelTitle: "Рэкамендаваная структура рэпазіторыя",
    repoPanelMeta: "project-repo/",
    repoAria: "Прыклад структуры рэпазіторыя",
    commandPanelTitle: "Адна кропка ўваходу для агента і CI",
    commandPanelMeta: "package.json",
    commandAria: "Прыклад npm-каманд eval",
    commandCalloutBefore: "Падчас працы агент запускае",
    commandCalloutMiddle: ", а перад завяршэннем —",
    commandCalloutAfter: ".",
    examplesLabel: "Прыклады канфігурацый eval",
    examples: {
      playwrightTitle: "Playwright: мабільнае меню",
      deterministic: "дэтэрміністычны",
      playwrightNote: "У рэальным тэсце лепш стварыць асобны helper для overflow, каб паведамленне пра failure было больш зразумелым.",
      lighthouseTitle: "Lighthouse CI: асцярожны бюджэт",
      labSignal: "лабараторны сігнал",
      lighthouseNote: "Лічбы — прыклад пачатковай палітыкі, а не ўніверсальны рэцэпт. Калібруйце іх на праекце і аддзяляйце лабараторныя вынікі ад field-метрык.",
      promptfooTitle: "Promptfoo: дадатковы эксперымент",
      later: "толькі пазней",
      promptfooNote: "Гэта каркас: custom provider павінен падрыхтаваць ізаляваную копію праекта, запусціць агента і вярнуць структураваны вынік, які грэйдар здольны прачытаць.",
    },
  },
  phases: {
    kicker: "07 · Фазы рэалізацыі",
    title: "Шэсць крокаў без «праекта фрэймворку»",
    intro: "Кожная фаза пакідае нешта карыснае. Калі спыніцца пасля трэцяй, у вас ужо будзе каштоўная лакальная сістэма eval.",
    items: [
      { number: "01", title: "Адзін рэальны сцэнар", text: "Наладзьце Playwright smoke-тэст для homepage і аднаго крытычнага flow, напрыклад мабільнай навігацыі.", deliverable: "npm run eval:browser" },
      { number: "02", title: "Хуткія guardrails", text: "Дадайце PHPCS/WPCS, PHPStan і наяўныя каманды lint для JS/CSS. Гэты слой запускаецца часта.", deliverable: "npm run eval:fast" },
      { number: "03", title: "Кантэнт edge case", text: "Увядзіце WP-CLI fixture для доўгага загалоўка, пустых палёў, незвычайнай выявы і доўгага меню.", deliverable: "tests/fixtures/" },
      { number: "04", title: "A11y і візуальны доказ", text: "Дадайце axe да ключавых станаў інтэрфейсу і невялікую колькасць стабільных baseline скрыншотаў.", deliverable: "npm run eval:full" },
      { number: "05", title: "CI як вароты", text: "Запускайце тыя ж каманды ў pull request. Захоўвайце скрыншот, trace і лог, калі тэст не праходзіць.", deliverable: "evidence artifacts" },
      { number: "06", title: "Promptfoo толькі калі спатрэбіцца", text: "Калі вы сапраўды параўноўваеце prompt-ы, мадэлі або агентаў на некалькіх паўтаральных задачах, дадайце эксперыментальны слой.", deliverable: "baseline vs candidate" },
    ],
    thresholdLabel: "Парог для цэнтралізацыі:",
    threshold: "вылучайце агульны пакет толькі тады, калі тое самае правіла або helper паўторыцца як мінімум у некалькіх рэальных тэмах і розніца паміж праектамі стане відавочнай.",
  },
  pitfalls: {
    kicker: "08 · Пасткі",
    title: "Як сістэма eval псуе сама сябе",
    items: [
      { title: "Агент змяняе тэст, каб яго прайсці", fix: "Ставіцеся да эвалоў, fixture і baseline як да абароненых файлаў. Змена крытэрыю патрабуе асобнага review." },
      { title: "Усё ацэньваецца LLM", fix: "Выкарыстоўвайце найтаннейшы грэйдар, які надзейна бачыць памылку. DOM, exit code і pixel diff маюць перавагу." },
      { title: "Толькі кантэнт happy path", fix: "Стварайце seed для пустых палёў, доўгіх загалоўкаў, праблемных URL, выяў з рознымі суадносінамі бакоў і глыбокіх меню." },
      { title: "Тэсты скрыншотаў нестабільныя", fix: "Трымайце baseline і выкананне ў адным browser/OS асяроддзі і маскіруйце толькі абгрунтавана дынамічныя часткі." },
      { title: "Ацэнка Lighthouse — адзіная ісціна", fix: "Усталюйце канкрэтныя бюджэты, паўтарайце лабараторныя вымярэнні і аддзяляйце іх ад field-даных рэальных карыстальнікаў." },
      { title: "Цэнтральныя правілы змяняюцца падчас запуску", fix: "Зафіксуйце версію eval bundle разам з commit, наборам fixture і runtime, каб той самы запуск можна было паўтарыць." },
    ],
  },
  checklist: {
    kicker: "Практычны старт",
    title: "Першыя 10 эвалоў для ўласнай тэмы",
    intro: "Пачніце тут. Кантрольны спіс наўмысна невялікі і сфакусаваны на паломках, якія ШІ найлягчэй уносіць, а наяўныя інструменты выразна выяўляюць.",
    resourcesCta: "Адкрыць афіцыйныя рэсурсы",
    items: [
      "Тэма актывуецца без памылак PHP fatal, warning і notice.",
      "Homepage, single, archive, search і 404 вяртаюць чаканы адказ.",
      "Мабільнае меню працуе з клавіятуры, а Escape вяртае фокус на trigger.",
      "Няма гарызантальнага overflow на 320, 375, 768 і 1440 px.",
      "Axe не мае ўзгодненых blocking violations у ключавых станах.",
      "Допіс без featured выявы і з пустымі дадатковымі палямі не ламае layout.",
      "Доўгі загаловак і непарыўны URL не выходзяць за межы кантэйнеру змесціва.",
      "PHPCS/WPCS і PHPStan праходзяць на ўзгодненым узроўні.",
      "Ключавыя template праходзяць ухваленыя baseline візуальнай рэгрэсіі.",
      "Поўны набор захоўвае зразумелы артэфакт доказу для кожнага blocking fail.",
    ],
  },
  resources: {
    kicker: "09 · Крыніцы",
    title: "Працягвайце з аўтарытэтнымі дакументамі",
    intro: "Спасылкі вядуць да афіцыйнай дакументацыі і першасных праектаў. Праверце версіі інструментаў і патрабаванні свайго праекта перад рэалізацыяй.",
    groups: [
      { group: "WordPress", links: [{ label: "Даведнік па тэставанні тэм", href: officialLinks.themeTesting }, { label: "Стандарты кода WordPress", href: officialLinks.wpcs }, { label: "E2E-тэсты з Playwright", href: officialLinks.wpPlaywright }] },
      { group: "Browser і якасць", links: [{ label: "Тэсты Playwright", href: officialLinks.playwright }, { label: "axe-core", href: officialLinks.axe }, { label: "Lighthouse CI", href: officialLinks.lighthouse }, { label: "Core Web Vitals", href: officialLinks.vitals }] },
      { group: "Слой eval для ШІ", links: [{ label: "Канфігурацыя Promptfoo", href: officialLinks.promptfooConfig }, { label: "Эвалы coding-agent у Promptfoo", href: officialLinks.promptfooAgents }, { label: "Архітэктура MCP", href: officialLinks.mcp }] },
    ],
  },
  final: {
    kicker: "Фінальная рэкамендацыя",
    title: "Не стварайце eval framework. Стварыце шлях даказвання.",
    text: "Лакальны harness + наяўныя грэйдары + fixtures + CI. Дадайце Promptfoo для эксперыментаў. Дадайце MCP толькі тады, калі існуе рэальны цэнтральны сэрвіс, якім павінны карыстацца некалькі кліентаў.",
  },
  footer: {
    title: "EDD для WordPress-тэм з дапамогай ШІ",
    text: "Адукацыйны дапаможнік · рэкамендацыі наўмысна паступовыя і vendor-neutral.",
    verified: "Крыніцы правераны 30 ліпеня 2026 г. ·",
    backToTop: "Наверх ↑",
  },
} satisfies GuideCopy;
