import type { GuideCopy } from "./types";
import { officialLinks } from "./shared";

export const ru = {
  locale: "ru",
  htmlLang: "ru",
  languageName: "Русский",
  shortLanguageName: "RU",
  meta: {
    title: "EDD для AI-assisted WordPress-тем",
    description:
      "Практическое руководство по Eval-Driven Development для AI-assisted разработки custom WordPress-тем.",
  },
  skipLink: "Перейти к содержимому",
  brand: {
    name: "EDD для WordPress",
    subtitle: "Практическое руководство",
    homeLabel: "EDD для WordPress — начало",
  },
  nav: {
    label: "Основная навигация",
    basics: "Основы",
    tools: "Инструменты",
    architecture: "Архитектура",
    start: "Старт",
    checklist: "Чек-лист",
  },
  languageMenu: {
    label: "Выберите язык",
    current: "Русский",
  },
  hero: {
    eyebrow: "Руководство для начинающих · 2026",
    titleLine1: "ИИ пишет код.",
    titleLine2: "Эвалы доказывают, что он работает.",
    lede:
      "Как внедрить Eval-Driven Development в разработку custom WordPress-темы — без создания нового framework, без MCP там, где он не нужен, и без опоры на «выглядит неплохо».",
    primaryCta: "Посмотреть рекомендуемую архитектуру",
    secondaryCta: "Открыть примеры",
    notePrefix: "Рекомендация в одном предложении:",
    noteStrong: "тесты рядом с проектом",
    noteSuffix:
      ", одна локальная eval-команда и Promptfoo — только при необходимости сравнивать агентов.",
    visualLabel: "Процесс Eval-Driven Development",
    flowCards: [
      { number: "01", title: "Задача", text: "ясное намерение" },
      { number: "02", title: "AI-агент", text: "изменяет тему" },
      { number: "03", title: "Eval harness", text: "запускает graders" },
      { number: "04", title: "Доказательство", text: "pass / fail + artifacts" },
    ],
    core: "EDD",
    coreText: "измеримое\n«готово»",
    caption: "Реализуй → проверь → исправь → повтори",
  },
  signals: {
    label: "Ключевые принципы",
    items: [
      { title: "Сначала детерминированные проверки", text: "наиболее стабильный сигнал" },
      { title: "Доказательство для каждого fail", text: "trace, log или screenshot" },
      { title: "Агент не меняет критерий", text: "eval остаётся независимым" },
    ],
  },
  basics: {
    kicker: "01 · Основы",
    title: "Что такое eval — без магии?",
    intro:
      "Eval — это воспроизводимая проверка, которая при известном входе измеряет, достигла ли система заранее определённого результата. В AI-assisted разработке измеряется результат агента, а не то, насколько убедительно звучит его ответ.",
    cards: [
      { letter: "A", title: "Вход", text: "Задача, исходный репозиторий, данные fixture, viewport и все разрешённые инструменты." },
      { letter: "B", title: "Ожидание", text: "Конкретный критерий: меню закрывается по Escape, нет PHP-ошибок, нет overflow." },
      { letter: "C", title: "Grader", text: "Самый простой надёжный способ измерения: assertion, linter, browser-тест или узкая rubric." },
      { letter: "D", title: "Evidence", text: "Pass/fail, фактическое значение, log, trace, screenshot и версии окружения." },
    ],
    loopLabel: "Цикл EDD: от критерия до исправления",
    loop: [
      { number: "1", text: "Определи «готово»" },
      { number: "2", text: "Запусти baseline" },
      { number: "3", text: "AI реализует" },
      { number: "4", text: "Eval измеряет" },
      { number: "5", text: "Исправь причину" },
    ],
  },
  graders: {
    kicker: "Правило выбора",
    title: "Самый дешёвый grader, который надёжно видит ошибку",
    intro:
      "LLM-as-a-judge полезен, но не должен решать задачу, которую DOM, parser, exit code или browser assertion решают точнее.",
    deterministic: {
      overline: "Первый выбор",
      title: "Детерминированный grader",
      text: "Одно и то же состояние даёт одинаковый, объяснимый результат. Он быстрый, недорогой и идеален как CI-gate.",
      tagsLabel: "Примеры детерминированных проверок",
      tags: ["HTTP 200", "ровно один H1", "нет overflow", "PHPCS exit 0", "Escape закрывает меню", "порог pixel diff"],
      exampleLabel: "Пример",
      example: "scrollWidth > clientWidth → FAIL",
    },
    model: {
      overline: "Только когда нужно",
      title: "Модельный grader",
      text: "Для нюансов, которые неразумно сводить к правилу. Rubric должна быть узкой, опираться на эталон и быть предварительно откалибрована.",
      tagsLabel: "Примеры модельных оценок",
      tags: ["соответствие Figma", "визуальная иерархия", "понятность UX редактора", "архитектурная оценка"],
      exampleLabel: "Хорошая rubric",
      example: "Оцени только spacing и alignment по шкале 0–5.",
    },
    ladderLabel: "Порядок выбора grader",
    ladder: ["assertion", "существующий инструмент", "custom-скрипт", "модельная rubric"],
  },
  tools: {
    kicker: "02 · Инструменты",
    title: "Какой инструмент видит какой тип ошибки?",
    intro:
      "Тебе не нужен один «супероценщик». Собери небольшие специализированные graders и используй каждый только там, где его сигнал надёжен.",
    boundaryLabel: "Ограничение",
    items: [
      { mark: "PW", name: "Playwright", tone: "mint", use: "Критические пользовательские сценарии, адаптивное поведение, мобильное меню, формы, ошибки консоли и горизонтальный overflow.", notFor: "Не заменяет unit-тесты; не стоит проверять им каждую мелочь.", link: officialLinks.playwright, linkLabel: "Документация Playwright" },
      { mark: "AX", name: "axe-core", tone: "violet", use: "Автоматически выявляемые проблемы accessibility: названия элементов управления, контраст, ARIA и часть правил WCAG.", notFor: "Автоматизация не доказывает, что весь сайт доступен; использование с клавиатурой и screen reader также требуют ручной проверки.", link: officialLinks.axe, linkLabel: "Документация axe-core" },
      { mark: "CS", name: "PHPCS + WPCS", tone: "amber", use: "Соглашения WordPress по коду, предупреждения об escaping, интернационализация и повторяемые проверки PHP-кода.", notFor: "Соответствие стандартам не означает, что бизнес-логика корректна.", link: officialLinks.wpcs, linkLabel: "Стандарты PHP для WordPress" },
      { mark: "PS", name: "PHPStan", tone: "blue", use: "Статический анализ: неизвестные классы и методы, неверные типы, мёртвые ветви и подозрительные вызовы до runtime.", notFor: "Для динамического WordPress-кода нужна постепенная настройка и подходящие stubs или расширения.", link: officialLinks.phpstan, linkLabel: "Руководство по началу работы с PHPStan" },
      { mark: "LH", name: "Lighthouse CI", tone: "coral", use: "Бюджеты производительности, размера ресурсов и выбранных результатов Lighthouse audit в контролируемой среде.", notFor: "Один лабораторный результат — не то же самое, что реальные пользовательские данные Core Web Vitals.", link: officialLinks.lighthouse, linkLabel: "Lighthouse CI" },
      { mark: "VR", name: "Visual regression", tone: "pink", use: "Сравнение screenshot ключевых шаблонов и компонентов для обнаружения неожиданных визуальных изменений.", notFor: "Baseline не обновляют лишь для того, чтобы тест стал зелёным: различие сначала должен проверить человек.", link: officialLinks.visual, linkLabel: "Визуальные сравнения Playwright" },
      { mark: "WP", name: "WP-CLI fixtures", tone: "green", use: "Воспроизводимое создание записей, меню, пользователей, настроек и контентных edge cases перед browser-тестом.", notFor: "Данные fixture — не production-контент и не должны попадать в production-пакет темы.", link: officialLinks.wpcli, linkLabel: "Команды WP-CLI" },
      { mark: "PU", name: "PHPUnit / WP test suite", tone: "slate", use: "Детерминированная PHP-логика, фильтры, helper-функции и интеграции, которые быстрее проверять без browser.", notFor: "Не может подтвердить фактический layout, фокус или взаимодействие в browser.", link: officialLinks.phpunit, linkLabel: "Шаблон тестов темы WordPress" },
    ],
  },
  architecture: {
    kicker: "03 · Архитектура",
    title: "Начни локально. Централизуй только то, что повторяется.",
    intro:
      "Для первого проекта достаточно repo-local harness. Центральный registry, Promptfoo и MCP — дополнительные слои, а не условие работы evals.",
    local: {
      badge: "Обязательно",
      title: "Локальный execution plane",
      intro: "Здесь находятся код, WordPress, browser и фактическое runtime-доказательство.",
      items: [
        { number: "01", title: "Исходный код темы", text: "AI изменяет реализацию" },
        { number: "02", title: "Настройка fixture", text: "WP-CLI или небольшой dev-only plugin" },
        { number: "03", title: "Eval-команды", text: "PHPCS · PHPStan · Playwright · axe" },
        { number: "04", title: "Evidence", text: "JSON · log · trace · screenshot" },
      ],
    },
    bridge: ["версионированный bundle", "структурированные результаты"],
    central: {
      badge: "Позже, при необходимости",
      title: "Центральный control plane",
      intro: "Здесь находятся общие правила, история и защищённые gates.",
      items: [
        { number: "A", title: "Общие стандарты", text: "company WPCS · a11y · performance" },
        { number: "B", title: "Project bundle", text: "точная, зафиксированная версия evals" },
        { number: "C", title: "Hidden / release evals", text: "проверки edge case и policy" },
        { number: "D", title: "История run", text: "тренды · сравнения · решения" },
      ],
    },
    ruleLabel: "Воспроизводимость:",
    rule: "source commit + версия eval bundle + версия fixture + версия runtime = воспроизводимый eval run.",
  },
  promptfoo: {
    kicker: "04 · Promptfoo",
    title: "Экспериментальный слой, а не WordPress grader",
    intro:
      "Promptfoo запускает матрицу prompts, providers и тестовых случаев, применяет assertions и сравнивает результаты. Твои инструменты WordPress по-прежнему доказывают, что тема работает.",
    flowLabel: "Роль Promptfoo в eval-системе",
    inputs: ["prompt A", "prompt B", "model / agent"],
    coreOverline: "experiment runner",
    coreText: "одни и те же задачи · контролируемое изменение",
    graders: ["Playwright", "PHPCS", "axe", "custom assertion"],
    resultOverline: "решение",
    resultTitle: "baseline vs candidate",
    resultText: "качество · стоимость · длительность",
    yesLabel: "ДА, когда…",
    yes: ["сравниваешь два prompt на одних и тех же задачах;", "измеряешь несколько моделей или конфигураций reasoning;", "у тебя есть 20+ повторяемых задач для coding-agent;", "тебе нужны история и матрица результатов без собственного UI."],
    noLabel: "ПОКА НЕТ, когда…",
    no: ["ты только внедряешь первый Playwright-тест;", "ты не сравниваешь агентов или prompts;", "тебе нужна лишь одна надёжная local-команда;", "Среда WordPress fixture ещё не стабильна."],
    cautionLabel: "Песочница",
    cautionBefore: "Запускай coding-agent eval в",
    cautionStrong: "disposable workspace",
    cautionAfter:
      ", без production credentials и реальных данных клиентов. Документация Promptfoo прямо предупреждает, что coding agents выполняют произвольный код.",
    cautionLink: "Официальное руководство по evals для coding-agent",
  },
  mcp: {
    kicker: "05 · MCP",
    title: "MCP — это слой доступа, а не test runner",
    intro:
      "MCP стандартизирует, как AI-приложение обнаруживает и вызывает tools, читает resources и использует prompts. Он не определяет, как должны быть реализованы твои Playwright, WordPress или CI.",
    yesTitle: "MCP имеет смысл для",
    yes: ["получения проектного eval bundle;", "чтения центральных стандартов и известных регрессий;", "отправки структурированных результатов и метаданных artifacts;", "сравнения предыдущих run из нескольких проектов;", "авторизованного доступа к центральному модельному grader."],
    noTitle: "MCP не нужен для",
    no: ["запуска npx playwright test локально;", "PHPCS, PHPStan и build-команд, которые агент уже может вызвать;", "хранения project-specific тестов рядом с кодом;", "WP-CLI seed и reset в локальном экземпляре;", "первой версии eval harness."],
    sourcePrefix: "Читайте:",
    sourceLink: "официальный обзор архитектуры MCP",
  },
  setup: {
    kicker: "06 · Минимальная настройка",
    title: "Рядом с source темы — но не в production ZIP",
    intro:
      "Репозиторий — правильная граница. Тесты остаются привязаны к commit темы, а поставляемый ZIP содержит только runtime-файлы.",
    repoPanelTitle: "Рекомендуемая структура репозитория",
    repoPanelMeta: "project-repo/",
    repoAria: "Пример структуры репозитория",
    commandPanelTitle: "Единая точка входа для агента и CI",
    commandPanelMeta: "package.json",
    commandAria: "Пример npm eval-команд",
    commandCalloutBefore: "В ходе работы агент запускает",
    commandCalloutMiddle: ", а перед завершением —",
    commandCalloutAfter: ".",
    examplesLabel: "Примеры конфигураций eval",
    examples: {
      playwrightTitle: "Playwright: мобильное меню",
      deterministic: "детерминированный",
      playwrightNote: "В реальном тесте лучше создать отдельный helper для overflow, чтобы сообщение о failure было понятнее.",
      lighthouseTitle: "Lighthouse CI: осторожный бюджет",
      labSignal: "лабораторный сигнал",
      lighthouseNote: "Числа — пример начальной политики, а не универсальный рецепт. Откалибруй их под проект и отделяй лабораторные результаты от field-метрик.",
      promptfooTitle: "Promptfoo: необязательный эксперимент",
      later: "только позднее",
      promptfooNote: "Это каркас: custom provider должен подготовить изолированную копию проекта, запустить агента и вернуть структурированный результат, который grader умеет прочитать.",
    },
  },
  phases: {
    kicker: "07 · Этапы внедрения",
    title: "Шесть шагов — без «проекта по созданию framework»",
    intro:
      "Каждый этап оставляет после себя что-то полезное. Если остановиться после третьего, у тебя уже будет ценная локальная eval-система.",
    items: [
      { number: "01", title: "Один реальный сценарий", text: "Настрой Playwright smoke-тест для homepage и одного критического flow, например мобильной навигации.", deliverable: "npm run eval:browser" },
      { number: "02", title: "Быстрые guardrails", text: "Добавь PHPCS/WPCS, PHPStan и существующие JS/CSS lint-команды. Этот слой запускается часто.", deliverable: "npm run eval:fast" },
      { number: "03", title: "Edge-case контент", text: "Добавь WP-CLI fixture для длинного заголовка, пустых полей, необычного изображения и длинного меню.", deliverable: "tests/fixtures/" },
      { number: "04", title: "A11y и визуальное доказательство", text: "Добавь axe для ключевых состояний интерфейса и небольшое число стабильных screenshot baseline.", deliverable: "npm run eval:full" },
      { number: "05", title: "CI как gate", text: "Запускай те же команды в pull request. Сохраняй screenshot, trace и log, когда тест падает.", deliverable: "evidence artifacts" },
      { number: "06", title: "Promptfoo — только когда понадобится", text: "Когда действительно сравниваешь prompts, модели или агентов на нескольких повторяемых задачах, добавь экспериментальный слой.", deliverable: "baseline vs candidate" },
    ],
    thresholdLabel: "Порог централизации:",
    threshold:
      "выделяй shared-пакет только когда одно и то же правило или helper повторится хотя бы в нескольких реальных темах и различия между проектами станут ясны.",
  },
  pitfalls: {
    kicker: "08 · Подводные камни",
    title: "Как eval-система может испортить сама себя",
    items: [
      { title: "Агент изменяет тест, чтобы пройти его", fix: "Относись к evals, fixture и baseline как к защищённым файлам. Изменение критерия требует отдельного review." },
      { title: "Всё оценивается LLM", fix: "Используй самый дешёвый grader, который надёжно видит ошибку. DOM, exit code и pixel diff имеют приоритет." },
      { title: "Только контент happy path", fix: "Создавай пустые поля, длинные заголовки, проблемные URL, изображения с разными соотношениями сторон и многоуровневые меню." },
      { title: "Screenshot-тесты нестабильны", fix: "Держи baseline и выполнение в одном browser/OS-окружении и маскируй только действительно динамичные части." },
      { title: "Lighthouse score — единственная истина", fix: "Установи конкретные бюджеты, повторяй лабораторные измерения и отделяй их от field-данных реальных пользователей." },
      { title: "Центральные правила меняются в середине run", fix: "Зафиксируй версию eval bundle вместе с commit, fixture set и runtime, чтобы тот же run можно было повторить." },
    ],
  },
  checklist: {
    kicker: "Практический старт",
    title: "Первые 10 evals для custom-темы",
    intro:
      "Начни здесь. Чек-лист намеренно небольшой и сфокусирован на проблемах, которые AI легче всего вносит, а существующие инструменты ясно выявляют.",
    resourcesCta: "Открыть официальные ресурсы",
    items: [
      "Тема активируется без PHP-ошибок fatal, warning и notice.",
      "Homepage, single, archive, search и 404 возвращают ожидаемый ответ.",
      "Мобильное меню работает с клавиатурой, а Escape возвращает фокус на trigger.",
      "Нет горизонтального overflow на 320, 375, 768 и 1440 px.",
      "Axe не выявляет согласованных blocking violations в ключевых состояниях.",
      "Запись без featured image и с пустыми необязательными полями не ломает layout.",
      "Длинный заголовок и неразрывный URL не выходят за пределы контейнера содержимого.",
      "PHPCS/WPCS и PHPStan проходят на согласованном уровне.",
      "Ключевые template проходят утверждённые visual regression baseline.",
      "Full suite сохраняет понятный evidence artifact для каждого blocking fail.",
    ],
  },
  resources: {
    kicker: "09 · Источники",
    title: "Продолжите с авторитетными документами",
    intro:
      "Ссылки ведут на официальную документацию и первичные проекты. Проверь версии инструментов и требования своего проекта до внедрения.",
    groups: [
      { group: "WordPress", links: [{ label: "Руководство по тестированию тем", href: officialLinks.themeTesting }, { label: "Стандарты кодирования WordPress", href: officialLinks.wpcs }, { label: "E2E-тесты с Playwright", href: officialLinks.wpPlaywright }] },
      { group: "Browser и качество", links: [{ label: "Тесты Playwright", href: officialLinks.playwright }, { label: "axe-core", href: officialLinks.axe }, { label: "Lighthouse CI", href: officialLinks.lighthouse }, { label: "Core Web Vitals", href: officialLinks.vitals }] },
      { group: "Слой AI eval", links: [{ label: "Конфигурация Promptfoo", href: officialLinks.promptfooConfig }, { label: "Promptfoo evals для coding-agent", href: officialLinks.promptfooAgents }, { label: "Архитектура MCP", href: officialLinks.mcp }] },
    ],
  },
  final: {
    kicker: "Итоговая рекомендация",
    title: "Не создавай eval framework. Создай путь доказательства.",
    text:
      "Локальный harness + существующие graders + fixtures + CI. Добавляй Promptfoo для экспериментов. Добавляй MCP только когда появится реальный центральный сервис, которым должны пользоваться несколько клиентов.",
  },
  footer: {
    title: "EDD для AI-assisted WordPress-тем",
    text: "Обучающее руководство · рекомендации намеренно поэтапные и vendor-neutral.",
    verified: "Источники проверены 30 июля 2026 г. ·",
    backToTop: "Наверх ↑",
  },
} satisfies GuideCopy;
