import { officialLinks } from "./shared";
import type { GuideCopy } from "./types";

export const srCyrl = {
  locale: "sr-cyrl",
  htmlLang: "sr-Cyrl",
  languageName: "Српски (ћирилица)",
  shortLanguageName: "СР Ћир",
  meta: {
    title: "Eval-Driven Development за AI-assisted WordPress теме",
    description:
      "Beginner-friendly водич за локалне evale, Playwright, axe, PHPCS, PHPStan, Lighthouse, Promptfoo и MCP у развоју custom WordPress тема.",
  },
  skipLink: "Прескочи навигацију",
  brand: {
    name: "EDD за WordPress",
    subtitle: "Практичан водич",
    homeLabel: "EDD за WordPress — почетак",
  },
  nav: {
    label: "Главна навигација",
    basics: "Основе",
    tools: "Алати",
    architecture: "Архитектура",
    start: "Старт",
    checklist: "Чеклиста",
  },
  languageMenu: {
    label: "Изабери језик",
    current: "Језик",
  },
  hero: {
    eyebrow: "Beginner-friendly водич · 2026",
    titleLine1: "AI пише код.",
    titleLine2: "Евали доказују да ради.",
    lede:
      "Како да уведеш Eval-Driven Development у израду custom WordPress теме — без прављења новог framework-а, без MCP-а тамо где није потребан и без ослањања на „делује добро“.",
    primaryCta: "Види препоручену архитектуру",
    secondaryCta: "Отвори примере",
    notePrefix: "Препорука у једној реченици:",
    noteStrong: "тестови уз пројекат",
    noteSuffix:
      ", један локални eval command и опциони Promptfoo тек за поређење агената.",
    visualLabel: "Ток Eval-Driven Development процеса",
    flowCards: [
      { number: "01", title: "Задатак", text: "јасан intent" },
      { number: "02", title: "AI агент", text: "мења тему" },
      { number: "03", title: "Eval harness", text: "покреће gradere" },
      { number: "04", title: "Доказ", text: "pass / fail + artifacts" },
    ],
    core: "EDD",
    coreText: "мерљиво\n„готово“",
    caption: "Имплементирај → провери → поправи → понови",
  },
  signals: {
    label: "Кључни принципи",
    items: [
      { title: "Детерминистички прво", text: "најстабилнији сигнал" },
      { title: "Доказ уз сваки fail", text: "trace, log или screenshot" },
      { title: "Агент не мења критеријум", text: "eval остаје независан" },
    ],
  },
  basics: {
    kicker: "01 · Основе",
    title: "Шта је eval — без магије?",
    intro:
      "Eval је поновљива провера која уз познат улаз мери да ли је систем постигао унапред дефинисан исход. Код AI-assisted развоја мери се резултат агента, а не колико његов одговор звучи уверљиво.",
    cards: [
      { letter: "A", title: "Улаз", text: "Task, почетни repo, fixture подаци, viewport и све дозвољене алатке." },
      { letter: "B", title: "Очекивање", text: "Конкретан критеријум: мени се затвара на Escape, нема PHP грешке, нема overflow-а." },
      { letter: "C", title: "Grader", text: "Најједноставнији поуздан начин мерења: assertion, linter, browser test или уска рубрика." },
      { letter: "D", title: "Evidence", text: "Pass/fail, стварна вредност, log, trace, screenshot и верзије окружења." },
    ],
    loopLabel: "EDD петља од критеријума до поправке",
    loop: [
      { number: "1", text: "Дефиниши „готово“" },
      { number: "2", text: "Покрени baseline" },
      { number: "3", text: "AI имплементира" },
      { number: "4", text: "Eval мери" },
      { number: "5", text: "Поправи узрок" },
    ],
  },
  graders: {
    kicker: "Правило избора",
    title: "Најјефтинији grader који поуздано види грешку",
    intro:
      "LLM-as-a-judge је користан, али не треба да решава проблем који DOM, parser, exit code или browser assertion решава прецизније.",
    deterministic: {
      overline: "Први избор",
      title: "Детерминистички grader",
      text: "Исто стање даје исти, објашњив резултат. Брз је, јефтин и идеалан као CI капија.",
      tagsLabel: "Примери детерминистичких провера",
      tags: ["HTTP 200", "тачно један H1", "нема overflow-а", "PHPCS exit 0", "Escape затвара мени", "pixel diff праг"],
      exampleLabel: "Пример",
      example: "scrollWidth > clientWidth → FAIL",
    },
    model: {
      overline: "Само када треба",
      title: "Модел grader",
      text: "За нијансе које није разумно свести на правило. Рубрика мора бити уска, референтна и претходно калибрисана.",
      tagsLabel: "Примери моделских процена",
      tags: ["верност Figmi", "визуелна хијерархија", "јасноћа editor UX-а", "архитектонска процена"],
      exampleLabel: "Добра рубрика",
      example: "Оцени само spacing и alignment 0–5.",
    },
    ladderLabel: "Редослед избора grader-а",
    ladder: ["assertion", "постојећи алат", "custom скрипта", "модел рубрика"],
  },
  tools: {
    kicker: "02 · Алати",
    title: "Који алат види коју врсту грешке?",
    intro:
      "Не треба ти један „super evaluator“. Сложи мале, специјализоване gradere и сваки користи само тамо где је његов сигнал поуздан.",
    boundaryLabel: "Граница",
    items: [
      { mark: "PW", name: "Playwright", tone: "mint", use: "Критични кориснички токови, responsive понашање, мобилни мени, форме, конзолне грешке и хоризонтални overflow.", notFor: "Није замена за unit тестове и не треба њиме тестирати сваку ситницу.", link: officialLinks.playwright, linkLabel: "Playwright документација" },
      { mark: "AX", name: "axe-core", tone: "violet", use: "Аутоматски препознатљиви accessibility проблеми: имена контрола, контраст, ARIA и део WCAG правила.", notFor: "Аутоматика не доказује да је цео сајт приступачан; тастатура и screen reader траже и ручну проверу.", link: officialLinks.axe, linkLabel: "axe-core документација" },
      { mark: "CS", name: "PHPCS + WPCS", tone: "amber", use: "WordPress coding конвенције, escaping упозорења, интернационализација и поновљиве провере PHP кода.", notFor: "Пролазак стандарда не значи да је пословна логика исправна.", link: officialLinks.wpcs, linkLabel: "WordPress PHP стандарди" },
      { mark: "PS", name: "PHPStan", tone: "blue", use: "Статичка анализа: непознате класе и методе, погрешни типови, мртве гране и сумњиви позиви пре runtime-а.", notFor: "За динамичан WordPress код треба постепено подешавање и одговарајуће stub-ове или екстензије.", link: officialLinks.phpstan, linkLabel: "PHPStan почетни водич" },
      { mark: "LH", name: "Lighthouse CI", tone: "coral", use: "Буџети за перформансе, величину ресурса и одабране Lighthouse audit резултате у контролисаном окружењу.", notFor: "Један лабораторијски резултат није исто што и стварни Core Web Vitals подаци корисника.", link: officialLinks.lighthouse, linkLabel: "Lighthouse CI" },
      { mark: "VR", name: "Visual regression", tone: "pink", use: "Screenshot поређење кључних template-а и компоненти ради хватања неочекиваних визуелних промена.", notFor: "Baseline се не ажурира само да би тест постао зелен; разлику прво мора прегледати човек.", link: officialLinks.visual, linkLabel: "Playwright visual comparisons" },
      { mark: "WP", name: "WP-CLI fixtures", tone: "green", use: "Поновљиво креирање post-ова, менија, корисника, опција и садржајних edge case-ова пре browser теста.", notFor: "Fixture подаци нису продукциони садржај и не треба да заврше у production пакету теме.", link: officialLinks.wpcli, linkLabel: "WP-CLI команде" },
      { mark: "PU", name: "PHPUnit / WP test suite", tone: "slate", use: "Детерминистичка PHP логика, филтери, helper-и и интеграције које је брже проверити без browser-а.", notFor: "Не може потврдити стварни layout, фокус или интеракцију у browser-у.", link: officialLinks.phpunit, linkLabel: "WordPress theme test scaffold" },
    ],
  },
  architecture: {
    kicker: "03 · Архитектура",
    title: "Почни локално. Централизуј тек оно што се понавља.",
    intro:
      "За први пројекат довољан је repo-local harness. Централни registry, Promptfoo и MCP су додатни слојеви — не услов да evali раде.",
    local: {
      badge: "Обавезно",
      title: "Локални execution plane",
      intro: "Ту су код, WordPress, browser и стварни runtime доказ.",
      items: [
        { number: "01", title: "Theme source", text: "AI мења имплементацију" },
        { number: "02", title: "Fixture setup", text: "WP-CLI или мали dev-only plugin" },
        { number: "03", title: "Eval commands", text: "PHPCS · PHPStan · Playwright · axe" },
        { number: "04", title: "Evidence", text: "JSON · log · trace · screenshot" },
      ],
    },
    bridge: ["верзионисани bundle", "структурирани резултати"],
    central: {
      badge: "Касније, по потреби",
      title: "Централни control plane",
      intro: "Ту живе заједничка правила, историја и заштићени gate-ови.",
      items: [
        { number: "A", title: "Shared standards", text: "company WPCS · a11y · performance" },
        { number: "B", title: "Project bundle", text: "тачна, закључана верзија eval-а" },
        { number: "C", title: "Hidden / release evals", text: "edge case и policy провере" },
        { number: "D", title: "Run history", text: "трендови · поређења · одлуке" },
      ],
    },
    ruleLabel: "Репродуктивност:",
    rule: "source commit + eval bundle верзија + fixture верзија + runtime верзија = поновљив eval run.",
  },
  promptfoo: {
    kicker: "04 · Promptfoo",
    title: "Експериментални слој, не WordPress grader",
    intro:
      "Promptfoo покреће матрицу prompt-ова, provider-а и test случајева, примењује assertions и пореди резултате. Твоји WordPress алати и даље доказују да тема ради.",
    flowLabel: "Улога Promptfoo-а у eval систему",
    inputs: ["prompt A", "prompt B", "model / agent"],
    coreOverline: "experiment runner",
    coreText: "исти задаци · контролисана промена",
    graders: ["Playwright", "PHPCS", "axe", "custom assertion"],
    resultOverline: "одлука",
    resultTitle: "baseline vs candidate",
    resultText: "квалитет · цена · трајање",
    yesLabel: "ДА, када…",
    yes: ["поредиш два prompt-а над истим задацима;", "мериш више модела или reasoning конфигурација;", "имаш 20+ поновљивих coding-agent задатака;", "желиш историју и матрицу резултата без свог UI-ја."],
    noLabel: "НЕ ЈОШ, када…",
    no: ["тек уводиш први Playwright тест;", "не поредиш агенте или prompt-ове;", "треба ти само један поуздан local command;", "WordPress fixture окружење још није стабилно."],
    cautionLabel: "Sandbox",
    cautionBefore: "Coding-agent eval покрећи у",
    cautionStrong: "disposable workspace-у",
    cautionAfter:
      ", без продукционих креденцијала и стварних клијентских података. Promptfoo документација изричито упозорава да coding агенти извршавају произвољан код.",
    cautionLink: "Званични водич за coding-agent evalе",
  },
  mcp: {
    kicker: "05 · MCP",
    title: "MCP је приступни слој, не test runner",
    intro:
      "MCP стандардизује како AI апликација открива и позива tools, чита resources и користи prompts. Не говори како твој Playwright, WordPress или CI треба да буду имплементирани.",
    yesTitle: "MCP има смисла за",
    yes: ["преузимање пројектног eval bundle-а;", "читање централних стандарда и познатих регресија;", "слање структурираних резултата и artifacts метаподатака;", "поређење претходних run-ова из више пројеката;", "ауторизован приступ централном model grader-у."],
    noTitle: "MCP није потребан за",
    no: ["покретање npx playwright test локално;", "PHPCS, PHPStan и build команде које агент већ може позвати;", "чување project-specific тестова уз код;", "WP-CLI seed и reset у локалној инстанци;", "прву верзију eval harness-а."],
    sourcePrefix: "Прочитај:",
    sourceLink: "званични преглед MCP архитектуре",
  },
  setup: {
    kicker: "06 · Минимални setup",
    title: "Уз source теме — али не у production ZIP-у",
    intro:
      "Repo је права граница. Тестови остају везани за commit теме, док испоручени ZIP садржи само runtime фајлове.",
    repoPanelTitle: "Препоручени repo layout",
    repoPanelMeta: "project-repo/",
    repoAria: "Пример структуре репозиторијума",
    commandPanelTitle: "Један улаз за агента и CI",
    commandPanelMeta: "package.json",
    commandAria: "Пример npm eval команди",
    commandCalloutBefore: "Агент током рада покреће",
    commandCalloutMiddle: ", а пре завршетка",
    commandCalloutAfter: ".",
    examplesLabel: "Примери eval конфигурација",
    examples: {
      playwrightTitle: "Playwright: мобилни мени",
      deterministic: "детерминистички",
      playwrightNote: "У реалном тесту радије направи посебан helper за overflow како би failure порука била јаснија.",
      lighthouseTitle: "Lighthouse CI: опрезан буџет",
      labSignal: "lab signal",
      lighthouseNote: "Бројеви су пример почетне политике, не универзални рецепт. Калибриши их на пројекту и одвоји лабораторијске резултате од field метрике.",
      promptfooTitle: "Promptfoo: опциони експеримент",
      later: "тек касније",
      promptfooNote: "Ово је костур: custom provider треба да припреми изоловану копију пројекта, покрене агента и врати структуриран резултат који grader уме да прочита.",
    },
  },
  phases: {
    kicker: "07 · Фазе имплементације",
    title: "Шест корака, без „framework пројекта“",
    intro:
      "Свака фаза оставља нешто употребљиво. Ако се зауставиш после треће, већ имаш вредан локални eval систем.",
    items: [
      { number: "01", title: "Један стварни ток", text: "Постави Playwright smoke test за homepage и један критичан flow, на пример мобилну навигацију.", deliverable: "npm run eval:browser" },
      { number: "02", title: "Брзи guardrails", text: "Додај PHPCS/WPCS, PHPStan и постојеће JS/CSS lint команде. Овај слој се покреће често.", deliverable: "npm run eval:fast" },
      { number: "03", title: "Edge-case садржај", text: "Уведи WP-CLI fixture за дуг наслов, празна поља, необичну слику и дугачак мени.", deliverable: "tests/fixtures/" },
      { number: "04", title: "A11y и визуелни доказ", text: "Додај axe на кључним стањима интерфејса и мали број стабилних screenshot baseline-а.", deliverable: "npm run eval:full" },
      { number: "05", title: "CI као капија", text: "Исте команде покрени на pull request-у. Сачувај screenshot, trace и log када test падне.", deliverable: "evidence artifacts" },
      { number: "06", title: "Promptfoo тек кад затреба", text: "Када заиста поредиш prompt-ове, моделе или агенте на више поновљивих задатака, додај експериментални слој.", deliverable: "baseline vs candidate" },
    ],
    thresholdLabel: "Праг за централизацију:",
    threshold:
      "издвоји shared пакет тек када се исто правило или helper понови на најмање неколико стварних тема и разлика међу пројектима постане јасна.",
  },
  pitfalls: {
    kicker: "08 · Замке",
    title: "Како eval систем сам себе поквари",
    items: [
      { title: "Агент мења тест да би прошао", fix: "Evale, fixture-е и baseline-е третирај као заштићене фајлове. Промена критеријума захтева засебан review." },
      { title: "Све се оцењује LLM-ом", fix: "Користи најјефтинији grader који поуздано види грешку. DOM, exit code и pixel diff имају предност." },
      { title: "Само happy path садржај", fix: "Seed-уј празна поља, дугачке наслове, проблематичне URL-ове, слике различитих односа и дубоке меније." },
      { title: "Screenshot тестови су нестабилни", fix: "Baseline и извршавање држи у истом browser/OS окружењу и маскирај само оправдано динамичне делове." },
      { title: "Lighthouse score је једина истина", fix: "Постави конкретне буџете, понови лабораторијска мерења и одвоји их од field података стварних корисника." },
      { title: "Централна правила се мењају усред run-а", fix: "Закључај верзију eval bundle-а уз commit, fixture set и runtime да би исти run могао да се понови." },
    ],
  },
  checklist: {
    kicker: "Практичан starter",
    title: "Првих 10 eval-а за custom тему",
    intro:
      "Почни овде. Чеклиста је намерно мала и фокусирана на кварове које AI најлакше уведе, а постојећи алати јасно детектују.",
    resourcesCta: "Отвори званичне ресурсе",
    items: [
      "Тема се активира без PHP fatal, warning и notice грешака.",
      "Homepage, single, archive, search и 404 враћају очекиван одговор.",
      "Мобилни мени ради тастатуром и Escape враћа фокус на trigger.",
      "Нема хоризонталног overflow-а на 320, 375, 768 и 1440 px.",
      "Axe нема договорене blocking violations на кључним стањима.",
      "Post без featured слике и са празним опционим пољима не ломи layout.",
      "Дуг наслов и непрекинут URL не излазе из садржајног контејнера.",
      "PHPCS/WPCS и PHPStan пролазе на договореном нивоу.",
      "Кључни template-и пролазе одобрене visual regression baseline-е.",
      "Full suite чува јасан evidence artifact за сваки blocking fail.",
    ],
  },
  resources: {
    kicker: "09 · Извори",
    title: "Настави са ауторитативним документима",
    intro:
      "Линкови воде ка званичној документацији и примарним пројектима. Провери верзије алата и захтеве свог пројекта пре имплементације.",
    groups: [
      { group: "WordPress", links: [{ label: "Theme testing handbook", href: officialLinks.themeTesting }, { label: "WordPress Coding Standards", href: officialLinks.wpcs }, { label: "E2E тестови са Playwright-ом", href: officialLinks.wpPlaywright }] },
      { group: "Browser и квалитет", links: [{ label: "Playwright тестови", href: officialLinks.playwright }, { label: "axe-core", href: officialLinks.axe }, { label: "Lighthouse CI", href: officialLinks.lighthouse }, { label: "Core Web Vitals", href: officialLinks.vitals }] },
      { group: "AI eval слој", links: [{ label: "Promptfoo конфигурација", href: officialLinks.promptfooConfig }, { label: "Promptfoo coding-agent evals", href: officialLinks.promptfooAgents }, { label: "MCP архитектура", href: officialLinks.mcp }] },
    ],
  },
  final: {
    kicker: "Коначна препорука",
    title: "Не прави eval framework. Направи доказни пут.",
    text: "Локални harness + постојећи graderи + fixtures + CI. Promptfoo додај за експерименте. MCP додај тек када постоји стварни централни сервис који више клијената треба да користи.",
  },
  footer: {
    title: "EDD за AI-assisted WordPress теме",
    text: "Едукативни водич · препоруке су намерно постепене и vendor-neutral.",
    verified: "Извори проверени 30. јула 2026.",
    backToTop: "Назад на врх ↑",
  },
} satisfies GuideCopy;
